Vagrant.configure("2") do |config|
  config.vm.box = "box-cutter/ubuntu1604-desktop"
  config.vm.provider "virtualbox" do |v|
    #v.gui = true
    v.memory = 8192
    v.cpus = 8
  end
  config.vm.provision "shell", inline: <<-SCRIPT
sudo apt update -y
sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" dist-upgrade
sudo apt-get autoremove -y
SCRIPT

end
