Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 4
  end
  config.vm.provision "shell", inline: <<-SCRIPT
sudo apt update -y
sudo apt full-upgrade -y
sudo apt-get autoremove -y
SCRIPT
end
